apiVersion: v1
kind: Service
metadata:
  name: {{ include "coredog.fullname" . }}-controller-grpc
  labels:
    {{- include "coredog.controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "coredog.controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 8443
      targetPort: {{ .Values.controller.service.grpcPort }}
      protocol: TCP
  type: ClusterIP
