apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coredog.fullname" . }}-controller
  labels:
    {{- include "coredog.controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "coredog.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coredog.controller.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          args: ["./coredog","controller"]
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "coredog.fullname" . }}
