fullnameOverride: coredog
nameOverride: coredog

image:
  repository: coderflyfyf/coredog
  tag: v0.0.3.rc

config:
  watcher.yaml: |-
    StorageConfig:
      enabled: true
      protocol: s3
      s3AccesskeyID: "s3AccesskeyID"
      s3SecretAccessKey: "s3SecretAccessKey"
      s3Region: "ap-nanjing"
      S3Bucket: "bucket"
      S3Endpoint: "endpoint"
      StoreDir: corefiles
      PresignedURLExpireSeconds: 3600
      DeleteLocalCorefile: true

  controller.yaml: |-
    NoticeChannel:
    - chan: slack
      webhookurl: "url"
    - chan: wechat
      webhookurl: "url"

controller:
  resources: {}
  service:
    grpcPort: 8443

watcher:
  resources: {}

corefileVolume:
  type: hostPath
  name: corefile
  hostPath:
    path: /root/core
    type: Directory
  emptyDir: {}
  persistentVolumeClaim:
    claimName: my-pvc
