name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        make build
        make push

    - name: Update image tag in values.yaml
      run: |
        sed -i "s/image\.tag: .*/image.tag: ${{ github.ref_name }}/" charts/values.yaml
        cat charts/values.yaml

    - name: Commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add charts/values.yaml
        git commit -m "Update image tag in values.yaml"
        git push

    - name: Create GitHub release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Docker image: user/repo:${{ github.ref_name }}
